### ISSUE TITLE
smc100pp Library Update Requests

### ISSUE THREAD

**Issue by danechever** [CaltechOpticalObservatories/hispec#11]
The library looks great and works very well! I just have a few requests:

1. The code should raise an error when you try to move while in an invalid state.
For example, right now if the user tries to move the stage while it is not referenced, the code just prints that the stage is not referenced but returns without issue or warning. It would be great if it gave more clear feedback that the move failed.
2. Add a function to check if the stage is homed.
Right now you can check the state and then you have to compare a string to imply if the stage is homed or not. Can we make a function that returns a boolean with this information?
3. Add a function to query the stage limits (if the controller supports this).

**Comment by scizen9** [comment]
Mostly fixed with PR#17

**Comment by scizen9** [comment]
With https://github.com/CaltechOpticalObservatories/hispec/pull/17 and https://github.com/CaltechOpticalObservatories/hispec/pull/21, these issues have been addressed.

**Comment by danechever** [comment]
It looks like doing a `move_abs()` on an un-referenced stage still doesn't throw an error or signal in any programmatic way that the move could not be done. It prints to the terminal that the stage is not referenced, but it doesn't stop execution. I guess this may be an implementation decision, but is the user meant to explicitly check before/after a move whether that move succeeded?

**Here's an example showing the current behavior:**
(Notice that the "NOT REFERENCED" is printed/logged, but the code proceeds without issue and without the stage actually moving.
```
>>> adc.get_state(stage_id=1)
{'elaptime': 0.05044150352478027, 'data': 'NOT REFERENCED from reset.'}
>>> 
>>> adc.homed(stage_id=1)
False
>>> 
>>> adc.get_position(stage_id=1)
{'elaptime': 0.05033993721008301, 'data': -0.0}
>>> 
>>> adc.move_abs(10, stage_id=1, blocking=True)
2025-05-28 15:18:49,427--NOT REFERENCED from reset.
{'elaptime': 0.05047488212585449, 'error': 'NOT REFERENCED from reset.'}
>>> 
>>> adc.get_position(stage_id=1)
{'elaptime': 0.05049705505371094, 'data': -0.0}
>>> 
```

**The expected behavior would be**

```
>>> adc.get_state(stage_id=1)
{'elaptime': 0.05044150352478027, 'data': 'NOT REFERENCED from reset.'}
>>> 
>>> adc.homed(stage_id=1)
False
>>> 
>>> adc.get_position(stage_id=1)
{'elaptime': 0.05033993721008301, 'data': -0.0}
>>> 
>>> adc.move_abs(10, stage_id=1, blocking=True)
2025-05-28 15:18:49,427--NOT REFERENCED from reset.
{'elaptime': 0.05047488212585449, 'error': 'NOT REFERENCED from reset.'}

[*** Raise Error Here, or provide some other programmatic signal that to know that the move did not execute ***]
```

**Comment by danechever** [comment]
Minor comment, not a big issue, but it seems that some non-error things are still being printed to console, even with `quiet=True`. 

1. get_params() - seems to print all the received parameters
2. move_abs() [with blocking] - prints '<timestamp> MOVING' while the move executes.

If this is a design decision, that's fine. Just figured I'd point it out if we expected `quite` to truly silence all non-error prints.

**Comment by scizen9** [comment]
These are all correct.  The move_abs does the right thing by returning an 'error' item.  It's up to the calling program to check for errors.  I don't think it's a good idea to throw an exception when the error is well defined.

For get_params, the whole point of the command is to print the commands.
When you are blocking, you will probably want to know that things are moving.

Both can be changed if the output is not desired.

BTW, it is better to open a new issue than make comments on old issues.
